version: "3"
services:
  nginx:
    build: ./
    ports:
    - 8080:443
    - 443:443
    volumes:
    - ./src:/usr/share/nginx/html
    - ./cert-key:/etc/nginx/certs





#  web:
#    image: nginx:alpine
#    ports:
#    - 8888:80
#    privileged: true
#    volumes:
#    - ".src/:usr/share/nginx/html"