version: "3"
services:
  nginx:
    build: ./
    ports:
    - 8080:443
    - 443:443
    volumes:
    - ./src:/usr/share/nginx/html
    - ./test1:/usr/share/nginx/test1
    - ./node_modules:/usr/share/nginx/node_modules
    - ./nginx.conf:/etc/nginx/nginx.conf
